@startuml 
package dnd { 
   abstract class Dungeon 
   abstract class Monster { 
         Attack 
         hasHealth: Health
      } 
   Dungeon o-- Monster 
   class Dragon 
   Dragon --|> Monster 
   class WhiteDragon 
   WhiteDragon --|> Dragon 
   class BlueDragon 
   BlueDragon --|> Dragon 
   class Kobold 
   Kobold --|> Monster 
   abstract class DragonLair 
   DragonLair --|> Dungeon 
   class WhiteDragonLair 
   WhiteDragonLair --|> DragonLair 
   } 
@enduml 
