@startuml 

package dnd
{
    abstract class Dungeon
    abstract class Monster

    Dragon --|> Monster
    WhiteDragon --|> Dragon
    BlueDragon --|> Dragon
    Kobold --|> Monster

    DragonLair --|> Dungeon
    WhiteDragonLair --|> DragonLair

    Dungeon o-- Monster
}

@enduml

