name: Build and lint check

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn --cwd ./oml-sprotty install
      - run: yarn --cwd ./oml-sprotty build
      - run: yarn install
      - run: yarn build
      - run: npm run lint
